import NxWelcome from '@mfe/libs/nx-welcome';

export const metadata = {
  title: 'Welcome to host',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <NxWelcome title="Next Host">{children}</NxWelcome>
      </body>
    </html>
  );
}
